React Native Web integration
Expensify/react-native-key-command pull request #9
Opened 2022-11-02 11:56 UTC by azimgd

to be merged first: https://github.com/Expensify/react-native-key-command/pull/8

2022-11-02 17:26 UTC, azimgd commented
@parasharrajat easy one, ready to be reviewed

2022-11-02 17:27 UTC, azimgd commented
Next step is to implement web version of the module

2022-11-03 09:09 UTC, parasharrajat requested changes

2022-11-03 09:09 UTC, parasharrajat commented on README.md
> +Objective-C and Java module that registers and listens to specified keyboard events, dispatching the payload to JavaScript.
May be

```suggestion
A cross-platform module that registers and listens to specified keyboard events, dispatching the payload to JavaScript.

✅ Android
✅ iOS
✅ Web
```

2022-11-03 09:09 UTC, parasharrajat commented on package.json
> +  "description": "Objective-C and Java module that registers and listens to specified keyboard events, dispatching the payload to JavaScript",
```suggestion
  "description": "A cross-platform module that registers and listens to specified keyboard events, dispatching the payload to JavaScript",
```

2022-11-03 09:13 UTC, parasharrajat approved these changes
LGTM.

cc: @luacmartins

2022-11-03 09:13 UTC, parasharrajat commented
Oh, there are conflicts.

2022-11-03 09:35 UTC, parasharrajat approved these changes

2022-11-03 15:51 UTC, luacmartins approved these changes

2022-11-03 15:51 UTC, merged